describe('Pokedex', function() {
  it('front page can be opened', function() {
    cy.visit(`https://bloglist-luke.fly.dev/`)
    cy.contains('Bloglist')
    cy.contains('log in')
  })
  it('user can log in, view details, create and interact with blogs ', function() {
    cy.visit(`https://bloglist-luke.fly.dev/`)
    cy.contains('log in').click()
    cy.get('#login-username-input').type('TESTUSER')
    cy.get('#login-password-input').type('1234')
    cy.get('[type=submit]').click()
    cy.contains('Hello TESTUSER')
    cy.get('.bloglist').find('.blog').should('have.length', 0)
    cy.contains('new blog').click()
    cy.get('input[name=title]').type('testString')
    cy.get('input[name=author]').type('testString')
    cy.get('input[name=url]').type('testString')
    cy.get('[type=submit]').click()
    cy.contains('a new blog testString by testString added')
    cy.contains('view').click()
    cy.contains('likes 0')
    cy.get('button.like').click()
    cy.contains('likes 1')
    cy.get('button.delete').click()
    cy.get('.bloglist').find('.blog').should('have.length', 0)
    cy.contains('logout').click()
    cy.contains('log in').click()
  })
})